### ISSUE TITLE
Error Cannot read property 'call' of undefined in events.js service.

### ISSUE THREAD

**Issue by BaR488** [isleofcode/ember-cordova-events#5]
I try do this:

```
import Ember from 'ember';
import subscribe from 'ember-cordova-events/utils/subscribe';

export default Ember.Route.extend({
  cordovaEvents: Ember.inject.service('ember-cordova/events'),

  logReady: subscribe('cordovaEvents.deviceready', function () {
    console.log('ready');
  }),

});
```

But in utils/subscribe.js :

`this.get(service).on(event, _listener);`
In services/ember-cordova/events.js:

```
on(name, target, method) {
    if (name === 'deviceready' && this._readyHasTriggered) {
      run.join(target, method);
    }
    return this._super(name, target, method);
  },
```

And then throw ecaption:

> TypeError: Cannot read property 'call' of undefined
>     at Backburner.join (vendor.js:11342)
>     at Function.run.join (vendor.js:33324)
>     at Class.on (vendor.js:73462)
>     at Class.superWrapper [as on] (vendor.js:51464)
>     at Class.computedFn [as logReady] (vendor.js:73559)
>     at Object.sendEvent (vendor.js:28853)
>     at new Class (vendor.js:47181)
>     at Function._ClassMixinProps.create (vendor.js:47367)
>     at instantiate (vendor.js:12289)
>     at DeprecatedFactoryManager.create (vendor.js:12424)

I use this guide http://embercordova.com/pages/addons/events.

**Comment by BaR488** [comment]
https://github.com/isleofcode/ember-cordova-events/pull/6

**Comment by alexblom** [comment]
Closing due to the merge of #6
